# Generated by Django 4.1.6 on 2023-02-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
