# Generated by Django 4.1.6 on 2023-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('el', 'electronic'), ('cl', 'clothing')], max_length=2)),
                ('title', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/products')),
                ('price', models.IntegerField()),
                ('discount', models.SmallIntegerField()),
                ('color', models.ManyToManyField(related_name='product', to='product.color')),
                ('size', models.ManyToManyField(related_name='product', to='product.size')),
            ],
        ),
    ]
