# Generated by Django 4.1.6 on 2023-02-17 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='tect',
            new_name='text',
        ),
    ]
