# Generated by Django 4.1.6 on 2023-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sluyg',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
